services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    buildCommand: "pip install -r setup.txt"
    startCommand: "python3 app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: 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  
